/**
 * Error codes for API responses
 * These codes are mapped to translation keys in the frontend
 */
export enum FileErrorCode {
  UNAUTHORIZED = 'FILE_UNAUTHORIZED',
  NO_FILES_PROVIDED = 'FILE_NO_FILES_PROVIDED',
  FAILED_TO_UPLOAD_ANY = 'FILE_FAILED_TO_UPLOAD_ANY',
  FOLDER_NOT_FOUND = 'FILE_FOLDER_NOT_FOUND',
  FAILED_TO_UPLOAD = 'FILE_FAILED_TO_UPLOAD',
  FAILED_TO_GET_FILES = 'FILE_FAILED_TO_GET_FILES',
  INVALID_FILE_ID = 'FILE_INVALID_FILE_ID',
  FILE_NOT_FOUND = 'FILE_NOT_FOUND',
  FAILED_TO_GET_FILE = 'FILE_FAILED_TO_GET_FILE',
  NO_FILE_PROVIDED = 'FILE_NO_FILE_PROVIDED',
  ONLY_ONE_FILE_VERSION = 'FILE_ONLY_ONE_FILE_VERSION',
  INVALID_FILE_NAME = 'FILE_INVALID_FILE_NAME',
  FILE_NOT_FOUND_OR_ACCESS_DENIED = 'FILE_NOT_FOUND_OR_ACCESS_DENIED',
  FAILED_TO_UPLOAD_NEW_VERSION = 'FILE_FAILED_TO_UPLOAD_NEW_VERSION',
  FAILED_TO_GET_VERSIONS = 'FILE_FAILED_TO_GET_VERSIONS',
  FILE_VERSION_NOT_FOUND = 'FILE_VERSION_NOT_FOUND',
  FAILED_TO_DOWNLOAD = 'FILE_FAILED_TO_DOWNLOAD',
  FILE_NAME_EXISTS = 'FILE_NAME_EXISTS',
  FAILED_TO_UPDATE = 'FILE_FAILED_TO_UPDATE',
  FAILED_TO_DELETE = 'FILE_FAILED_TO_DELETE',
  CANNOT_UPLOAD_TO_FOLDER = 'FILE_CANNOT_UPLOAD_TO_FOLDER',
  CANNOT_UPLOAD_TO_GENERAL = 'FILE_CANNOT_UPLOAD_TO_GENERAL',
  FILES_ONLY_IN_MY_FOLDERS = 'FILE_FILES_ONLY_IN_MY_FOLDERS',
  FILES_MUST_BE_IN_SYSTEM_FOLDER = 'FILE_FILES_MUST_BE_IN_SYSTEM_FOLDER',
  CANNOT_MOVE_TO_GENERAL = 'FILE_CANNOT_MOVE_TO_GENERAL',
  FILES_ONLY_MOVE_TO_MY_FOLDERS = 'FILE_FILES_ONLY_MOVE_TO_MY_FOLDERS',
}

